# Generated by Django 4.2.4 on 2023-09-27 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 8, 50, 19, 462856, tzinfo=datetime.timezone.utc)),
        ),
    ]
