# Generated by Django 4.2.4 on 2023-09-27 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 23, 21, 37, 760580, tzinfo=datetime.timezone.utc)),
        ),
    ]
