# Generated by Django 4.2.4 on 2023-09-28 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 3, 44, 0, 604429, tzinfo=datetime.timezone.utc)),
        ),
    ]
