# Generated by Django 4.2.4 on 2023-09-29 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 2, 35, 28, 26753, tzinfo=datetime.timezone.utc)),
        ),
    ]
