# Generated by Django 4.2.4 on 2023-10-05 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 15, 16, 10, 503000, tzinfo=datetime.timezone.utc)),
        ),
    ]
